CREATE DATABASE PORTFOLIOMANAGER;
USE PORTFOLIOMANAGER;

CREATE TABLE IF NOT EXISTS `ADMIN' (
  `ADMIN_EMAIL` VARCHAR(50) NOT NULL,
  `ADMIN_PASSWORD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ADMIN_EMAIL`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `PROJECT` (
	`PROJECT_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT
  , `PROJECT_NAME` VARCHAR(100) NOT NULL
  , `PROJECT_DESCRIPTION` VARCHAR(300) NOT NULL
  , `PROJECT_IMG` VARCHAR(500) NOT NULL
  , `PROJECT_URL` VARCHAR(500) NOT NULL
  , `ADMIN_EMAIL` VARCHAR(50) NOT NULL
  , PRIMARY KEY (`PROJECT_IDX`),
	KEY `PROJECT_FK_1` (`ADMIN_EMAIL`),
	CONSTRAINT `PROJECT_FK_1` FOREIGN KEY (`ADMIN_EMAIL`) REFERENCES `ADMIN` (`ADMIN_EMAIL`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;